available:
  videos:
    - title: exploring
      ytId: K69tbUo3vGs
    - title: dark-omnious
      ytId: CDWtH8eHeEU'
    - title: snowy-harry-potter
      ytId: oE-pXV-G9aY
    - title: dark-fantasy
      ytId: WUhMLw6vq8g
    - title: epic-of-epic
      ytId: 9O4_awEHh1g
    - title: tavern
      ytId: vyg5jJrZ42s
    - title: classical-evil
      ytId: Q0OhmGD-4-E
    - title: dark-out-of-combat
      ytId: WUhMLw6vq8g
    - title: combat
      ytId: CLAa1urufGE